version: "3.8"

services:
  execution:
    image: ethpandaops/erigon:2.53.0
    user: "root"
    command:
      --log.console.verbosity=3
      --datadir=/execution-data
      --port=50503
      --networkid=28256
      --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin,ots
      --http.vhosts=*
      --ws
      --allow-insecure-unlock
      --nat=extip:${IP_ADDRESS}
      --http
      --http.addr=0.0.0.0
      --http.corsdomain=*
      --http.port=8545
      --authrpc.jwtsecret=/el-cl-genesis-data/jwt/jwtsecret
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts=*
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=9001
      --bootnodes=enode://30674d1f5fa3cf763c2d991eeaf585db42c45737a4d47aee3653b50ac33947437769e13f04c12bab63d5c2a416d08b2637e6340d13b7d59489f0ac8dae919756@88.99.94.109:50303
      --staticpeers=enode://30674d1f5fa3cf763c2d991eeaf585db42c45737a4d47aee3653b50ac33947437769e13f04c12bab63d5c2a416d08b2637e6340d13b7d59489f0ac8dae919756@88.99.94.109:50303
    volumes:
      - ./execution-data:/execution-data
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "11545:8545" 
      - "11546:8546" 
      - "11551:8551" 
      - "18501:9001" 
      - "52503:50503"
    restart: unless-stopped

  beacon:
    image: consensys/teku:latest
    user: "root"
    command:
      - --logging=INFO 
      - --log-destination=CONSOLE 
      - --network=/el-cl-genesis-data/custom_config_data/config.yaml 
      - --initial-state=/el-cl-genesis-data/custom_config_data/genesis.ssz 
      - --data-path=/opt/teku/consensus-data 
      - --data-storage-mode=ARCHIVE 
      - --p2p-enabled=true 
      - --p2p-subscribe-all-subnets-enabled=true 
      - --p2p-peer-lower-bound=1 
      - --p2p-advertised-ip=${IP_ADDRESS}
      - --p2p-discovery-site-local-addresses-enabled 
      - --rest-api-enabled=true 
      - --rest-api-docs-enabled=true 
      - --rest-api-interface=0.0.0.0 
      - --rest-api-port=4000 
      - --rest-api-host-allowlist=* 
      - --data-storage-non-canonical-blocks-enabled=true 
      - --ee-jwt-secret-file=/el-cl-genesis-data/jwt/jwtsecret 
      - --ee-endpoint=http://execution:8551 
      - --metrics-enabled 
      - --metrics-interface=0.0.0.0 
      - --metrics-host-allowlist='*' 
      - --metrics-categories=BEACON,PROCESS,LIBP2P,JVM,NETWORK,PROCESS 
      - --metrics-port=8008 
      - --Xtrusted-setup=/el-cl-genesis-data/custom_config_data/trusted_setup.txt 
      - --validators-external-signer-public-keys=http://88.99.94.109:49100/api/v1/eth2/publicKeys
      - --validators-external-signer-url=http://88.99.94.109:49100
      - --validators-proposer-default-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776 
      - --p2p-discovery-bootnodes=enr:-Ma4QDCZLvwSpUnbRMG5bh2J5H4Dx4FCikjUsPwW4Dmt390TINwdOHcFMPsv2HQOfPmJdmgXdEYJ5vqeEhO8Z_hbBByCBX6HYXR0bmV0c4j__________4RldGgykCO-TCBQAAA4QEIPAAAAAACCaWSCdjSCaXCEWGNebYRxdWljgir5iXNlY3AyNTZrMaECg2F8MDnul4GF8qWBFENgqaPA5Q9I-qP3uGlabDJyAl2Ic3luY25ldHMPg3RjcIIq-IN1ZHCCKvg
      - --p2p-static-peers=/ip4/88.99.94.109/tcp/11000/p2p/16Uiu2HAm4GXc2aYZkdfHvvn56s6zEdoSAwdiNcGkzvXX5y4MX4U4
      - --p2p-port=11500
    volumes:
      - ./consensus-data:/consensus-data 
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "11500:11500"
      - "5409:4000"
      - "9409:8008"
    depends_on:
      - execution
    restart: unless-stopped
